export const studentsData = [
  {
    name: "Sofía",
    wallet: "0x752c9459Bb3A76caFF270bbe7b8e20A71A67648A",
    bio: "Soy Sofía. Desde pequeña, amo bailar. Sueño con ser una bailarina profesional y viajar por el mundo compartiendo mi pasión por el baile.",
    grade: "2o Primaria",
    country: "Colombia",
    attendance: 99,
    average: 89,
    extracurriculares: 97,
    image_url: "https://i.ibb.co/x5H7gLG/girl.png",
    collectibleBalances: [3, 5, 0, 1, 0, 2, 0, 0, 0],
  },
  {
    name: "Mario",
    wallet: "0x4C0917751f5A4c429d3bf5E82A8e295364976742",
    bio: "Hola, soy Mario. Sueño con tener mi propia granja para cultivar alimentos saludables. Me encanta la naturaleza y quiero aprender a cuidarla mejor.",
    grade: "4o Primaria",
    country: "México",
    attendance: 97,
    average: 91,
    extracurriculares: 85,
    image_url: "https://i.ibb.co/txD6D7R/farmer.png",
    collectibleBalances: [3, 5, 0, 1, 0, 2, 0, 0, 0],
  },
  {
    name: "Diego",
    wallet: "0x3a0D920a577706774b986596F19EFbA325ef0aCF",
    bio: "Hola, soy Diego. Me encantan los deportes y la ciencia. Aunque aún no sé qué quiero ser, estoy seguro de que quiero hacer algo que me apasione.",
    grade: "6o Primaria",
    country: "Chile",
    attendance: 95,
    average: 89,
    extracurriculares: 97,
    image_url: "https://i.ibb.co/H7bZCk0/happy-kid-2.png",
    collectibleBalances: [3, 5, 0, 1, 0, 2, 0, 0, 0],
  },
  {
    name: "Sebastián",
    wallet: "0x48978BDF217d839654fba20e0B40ee179A55e621",
    bio: "Hola, soy Sebastián. Me apasionan los animales y el medio ambiente. Aunque aún no sé qué carrera seguir, quiero hacer algo que ayude a proteger nuestro planeta.",
    grade: "3o Preparatoria",
    country: "Costa Rica",
    attendance: 98,
    average: 89,
    extracurriculares: 97,
    image_url: "https://i.ibb.co/jh8Fhwk/graduate.png",
    collectibleBalances: [3, 5, 0, 1, 0, 2, 0, 0, 0],
  },
  {
    name: "Lucas",
    wallet: "0x752c9459Bb3A76caFF270bbe7b8e20A71A67648A",
    bio: "¡Hola! Soy Lucas. Me encanta leer y enseñar a mis amigos. Mi sueño es ser maestro para ayudar a otros niños a aprender y alcanzar sus sueños.",
    grade: "4o Primaria",
    country: "Argentina",
    attendance: 96,
    average: 89,
    extracurriculares: 97,
    image_url: "https://i.ibb.co/BgDrg4y/teacher.png",
    collectibleBalances: [3, 5, 0, 1, 0, 2, 0, 0, 0],
  },
  {
    name: "Carlos",
    wallet: "0x4C0917751f5A4c429d3bf5E82A8e295364976742",
    bio: "Soy Carlos. Me gusta mucho el arte y la tecnología. Aunque no estoy seguro de qué quiero ser, sé que quiero combinar estas dos pasiones en mi futuro.",
    grade: "3o Secundaria",
    country: "Panamá",
    attendance: 99,
    average: 99,
    extracurriculares: 97,
    image_url: "https://i.ibb.co/BPBJXwn/student.png",
    collectibleBalances: [3, 5, 0, 1, 0, 2, 0, 0, 0],
  },
  {
    name: "Camilo",
    wallet: "0x3a0D920a577706774b986596F19EFbA325ef0aCF",
    bio: "¡Hola! Soy Camilo. Me gusta mucho la música y las manualidades. Aún no sé qué quiero ser, pero sé que quiero crear cosas hermosas.",
    grade: "2o Primaria",
    country: "Perú",
    attendance: 97,
    average: 89,
    extracurriculares: 97,
    image_url: "https://i.ibb.co/1dCC6gt/happy-kid.png",
    collectibleBalances: [3, 5, 0, 1, 0, 2, 0, 0, 0],
  },
  {
    name: "Valeria",
    wallet: "0x48978BDF217d839654fba20e0B40ee179A55e621",
    bio: "¡Hola! Soy Valeria. Mi pasión es el patinaje sobre hielo. Sueño con competir en campeonatos internacionales y ganar medallas para mi país.",
    grade: "2o Preparatoria",
    country: "Brasil",
    attendance: 95,
    average: 92,
    extracurriculares: 99,
    image_url: "https://i.ibb.co/b1XsmMm/ice-skater.png",
    collectibleBalances: [3, 5, 0, 1, 0, 2, 0, 0, 0],
  },
  {
    name: "Fernanda",
    wallet: "0x752c9459Bb3A76caFF270bbe7b8e20A71A67648A",
    bio: "Hola, soy Fernanda. Mi sueño es ser una snowboarder profesional y representar a mi país en competiciones internacionales. Me encanta la adrenalina de este deporte.",
    grade: "3o Preparatoria",
    country: "Argentina",
    attendance: 93,
    average: 84,
    extracurriculares: 100,
    image_url: "https://i.ibb.co/c27Nt8k/snowboarder.png",
    collectibleBalances: [3, 5, 0, 1, 0, 2, 0, 0, 0],
  },
  {
    name: "Andrés",
    wallet: "0x4C0917751f5A4c429d3bf5E82A8e295364976742",
    bio: "Soy Andrés. Mi sueño es ser un payaso y llevar alegría a los niños en todo el mundo. Creo que la risa es muy importante y quiero compartir felicidad.",
    grade: "1o Primaria",
    country: "Colombia",
    attendance: 96,
    average: 82,
    extracurriculares: 96,
    image_url: "https://i.ibb.co/0ydJ92z/clown.png",
    collectibleBalances: [3, 5, 0, 1, 0, 2, 0, 0, 0],
  },
  {
    name: "Miguel",
    wallet: "0x3a0D920a577706774b986596F19EFbA325ef0aCF",
    bio: "¡Hola! Soy Miguel. Me fascina el circo y sueño con ser un malabarista famoso. Quiero viajar y hacer sonreír a la gente con mis trucos.",
    grade: "3o Primaria",
    country: "Uruguay",
    attendance: 98,
    average: 89,
    extracurriculares: 92,
    image_url: "https://i.ibb.co/cQcDg4J/jester.png",
    collectibleBalances: [3, 5, 0, 1, 0, 2, 0, 0, 0],
  },
  {
    name: "Juan",
    wallet: "0x48978BDF217d839654fba20e0B40ee179A55e621",
    bio: "Soy Juan. Me fascina el cine y sueño con ser un doble de actuación. Quiero realizar escenas emocionantes y ser parte de grandes películas.",
    grade: "2o Primaria",
    country: "Venezuela",
    attendance: 90,
    average: 89,
    extracurriculares: 97,
    image_url: "https://i.ibb.co/x1GXnG3/stuntman.png",
    collectibleBalances: [3, 5, 0, 1, 0, 2, 0, 0, 0],
  },
];
